/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rmsmama;

import rmsmama.Login;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Fritz
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    
    JpanelLoader jpload = new JpanelLoader();
    
    public AdminDashboard() {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(AdminDashboard.MAXIMIZED_BOTH);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        manageCategoryBTN = new javax.swing.JButton();
        posBTN = new javax.swing.JButton();
        employeeBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        positionBTN = new javax.swing.JButton();
        logoutBTN = new javax.swing.JButton();
        manageProductBTN = new javax.swing.JButton();
        accountBTN = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panel_load = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1360, 710));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        manageCategoryBTN.setBackground(new java.awt.Color(255, 204, 255));
        manageCategoryBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        manageCategoryBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rmsmama/icons/category.png"))); // NOI18N
        manageCategoryBTN.setText("Manage Category");
        manageCategoryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCategoryBTNActionPerformed(evt);
            }
        });

        posBTN.setBackground(new java.awt.Color(204, 255, 255));
        posBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        posBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rmsmama/icons/POS.png"))); // NOI18N
        posBTN.setText("POS");
        posBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posBTNActionPerformed(evt);
            }
        });

        employeeBTN.setBackground(new java.awt.Color(255, 204, 204));
        employeeBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        employeeBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rmsmama/icons/employee.png"))); // NOI18N
        employeeBTN.setText("Employee");
        employeeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeBTNActionPerformed(evt);
            }
        });

        exitBTN.setBackground(new java.awt.Color(204, 204, 204));
        exitBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rmsmama/icons/exit.png"))); // NOI18N
        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        positionBTN.setBackground(new java.awt.Color(255, 255, 204));
        positionBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        positionBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rmsmama/icons/position.png"))); // NOI18N
        positionBTN.setText("Job Position");
        positionBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionBTNActionPerformed(evt);
            }
        });

        logoutBTN.setBackground(new java.awt.Color(204, 204, 204));
        logoutBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rmsmama/icons/logout.png"))); // NOI18N
        logoutBTN.setText("Logout");
        logoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTNActionPerformed(evt);
            }
        });

        manageProductBTN.setBackground(new java.awt.Color(204, 204, 255));
        manageProductBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        manageProductBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rmsmama/icons/product.png"))); // NOI18N
        manageProductBTN.setText("Manage Product");
        manageProductBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProductBTNActionPerformed(evt);
            }
        });

        accountBTN.setBackground(new java.awt.Color(204, 255, 204));
        accountBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        accountBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rmsmama/icons/accounts.png"))); // NOI18N
        accountBTN.setText("Accounts");
        accountBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountBTNActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rmsmama/icons/invoice.png"))); // NOI18N
        jButton2.setText("Sales");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageProductBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageCategoryBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(posBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(employeeBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(positionBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accountBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(posBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageProductBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageCategoryBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(employeeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(positionBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(accountBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(logoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        panel_load.setBackground(new java.awt.Color(255, 204, 102));
        panel_load.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_load.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rmsmama/pics/bg5.png"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_load.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panel_load, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 1110, 554));

        jPanel5.setBackground(new java.awt.Color(255, 204, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1336, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 1340, -1));

        jPanel6.setBackground(new java.awt.Color(255, 204, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1336, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1340, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void posBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posBTNActionPerformed
        POS p = new POS();
                    p.setVisible(true);
                    
                    this.setVisible(false);
    }//GEN-LAST:event_posBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Exit?","Select", JOptionPane.YES_NO_OPTION);
        if (a == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_exitBTNActionPerformed

    private void employeeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeBTNActionPerformed
        Employee em = new Employee();
        jpload.jPanelLoader(panel_load, em);
    }//GEN-LAST:event_employeeBTNActionPerformed

    private void manageProductBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProductBTNActionPerformed
        ManageProduct mp = new ManageProduct();
        jpload.jPanelLoader(panel_load, mp);
    }//GEN-LAST:event_manageProductBTNActionPerformed

    private void manageCategoryBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCategoryBTNActionPerformed
        ManageCategory mc = new ManageCategory();
        jpload.jPanelLoader(panel_load, mc);
    }//GEN-LAST:event_manageCategoryBTNActionPerformed

    private void positionBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionBTNActionPerformed
        Position po = new Position();
        jpload.jPanelLoader(panel_load, po);
    }//GEN-LAST:event_positionBTNActionPerformed

    private void logoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTNActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to logout?","Select", JOptionPane.YES_NO_OPTION);
        if (a == 0){
            Login l = new Login();
                    l.setVisible(true);
                    
                    this.setVisible(false);
        }
    }//GEN-LAST:event_logoutBTNActionPerformed

    private void accountBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountBTNActionPerformed
        Accounts acc = new Accounts();
        jpload.jPanelLoader(panel_load, acc);
    }//GEN-LAST:event_accountBTNActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Invoice inv = new Invoice();
        jpload.jPanelLoader(panel_load, inv);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountBTN;
    private javax.swing.JButton employeeBTN;
    private javax.swing.JButton exitBTN;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton logoutBTN;
    private javax.swing.JButton manageCategoryBTN;
    private javax.swing.JButton manageProductBTN;
    private javax.swing.JPanel panel_load;
    private javax.swing.JButton posBTN;
    private javax.swing.JButton positionBTN;
    // End of variables declaration//GEN-END:variables
}
